# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_search}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mauricio Zaffari"]
  s.date = %q{2011-04-07}
  s.description = %q{Simple full text search implementation.}
  s.email = %q{mauricio@papodenerd.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/mongoid_search.rb",
     "lib/mongoid_search/mongoid_search.rb",
     "lib/mongoid_search/util.rb",
     "mongoid_search.gemspec",
     "spec/config/ignorelist.yml",
     "spec/models/category.rb",
     "spec/models/product.rb",
     "spec/models/subproduct.rb",
     "spec/models/tag.rb",
     "spec/mongoid_search_spec.rb",
     "spec/spec_helper.rb",
     "spec/util_spec.rb"
  ]
  s.homepage = %q{http://www.papodenerd.net/mongoid-search-full-text-search-for-your-mongoid-models/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Search implementation for Mongoid ORM}
  s.test_files = [
    "spec/models/category.rb",
     "spec/models/product.rb",
     "spec/models/subproduct.rb",
     "spec/models/tag.rb",
     "spec/mongoid_search_spec.rb",
     "spec/spec_helper.rb",
     "spec/util_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

